@startuml
'https://plantuml.com/sequence-diagram

class RECT{
-px
-py
-dx
-dy
+onClick(x,y)
+onMove(x,y)
+onKeypress(key)
+Draw_border(x,y,dx,dy)
+Draw_pic(x,y,pic)
+Draw_Text(x,y,text)
+Draw_Fill(x,y,dx,dy,color)
}

class Door{
-Titulo: String
-Salir: String
-Enviar: String
-TamañoPestaña: picture
-Minimizar: picture
+onKeypress(key)
+onClick(x,y)
}

class Teclado{
-key
+onKeypress(key)
}

class Ratón{
-px
-py
-dx
-dy
+onClick(x,y)
+onMove(x,y)
}

RECT <|--- Door
Teclado<|---- RECT
Ratón<|---- RECT
@enduml